# _config.yml

# Site settings
title: Chi's GitHub Pages Site
description: This is Chi's GitHub Pages site recording his life and research as a PhD student 
baseurl: ""

# Theme settings
theme: jekyll-theme-Type-on-Strap

